#
# Run pre-commit hooks. You can run them without installing
#  the hook with
#
# $ pre-commit run --all-files
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    # Manage spaces.
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-symlinks
    # Check file syntax/format
    - id: check-xml
    - id: check-json
    - id: check-yaml
      args: [--allow-multiple-documents]
    # Security checks.
    - id: detect-private-key
    - id: detect-aws-credentials
      args:
      # See https://github.com/pre-commit/pre-commit-hooks/issues/174
      - --allow-missing-credentials
