name: Deploy Schema Editor

# Trigger su push al branch di test o main
on:
  push:
    branches:
      - build-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installa le dipendenze
      - name: Install dependencies
        run: npm ci

      # Build del progetto
      - name: Build project
        run: npm run build

      # Deploy su gh-pages con latest & previous
      - name: Deploy latest & previous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Clona il repository usando token per push
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
          cd gh-pages || exit

          # Controlla se esiste il branch gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            # Crea branch gh-pages vuoto
            git checkout --orphan gh-pages
            git rm -rf .
          fi

          # Aggiorna previous
          if [ -d latest ]; then
            rm -rf previous
            mv latest previous
          fi

          # Aggiorna latest con la nuova build
          rm -rf latest
          mkdir latest
          cp -r ../dist/* latest/

          # Configura git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Commit & push
          git add .
          git commit -m "Deploy new build: update latest and previous" || echo "No changes to commit"
          git push origin gh-pages --force
