name: Deploy Schema Editor

on:
  push:
    branches:
      - build-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy latest & previous
        run: |
          # Clona branch gh-pages
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages || exit

          # Aggiorna previous
          rm -rf previous
          if [ -d latest ]; then
            mv latest previous
          fi

          # Aggiorna latest
          mkdir latest
          cp -r ../dist/* latest/

          # Commit & push
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Deploy new build: update latest and previous"
          git push origin gh-pages
