name: Deploy Schema Editor

on:
  push:
    branches:
      - build-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout codice sorgente
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installa dipendenze
      - name: Install dependencies
        run: npm ci

      # Build progetto (ferma il job se fallisce)
      - name: Build project
        run: |
          set -e
          npm run build
          echo "✅ Build completata correttamente"

      # Deploy latest & previous su gh-pages
      - name: Deploy latest & previous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e

          # Clona il branch gh-pages se esiste
          if git ls-remote --exit-code --heads https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages; then
            git clone --branch gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
          else
            git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} gh-pages
            cd gh-pages
            git checkout --orphan gh-pages
            git rm -rf .
            cd ..
          fi

          cd gh-pages

          # Se esiste latest, spostala in previous
          if [ -d latest ]; then
            echo "Sposto latest in previous"
            rm -rf previous
            mv latest previous
          else
            echo "Nessuna build precedente, creo cartella previous vuota"
            mkdir -p previous
          fi

          # Copia nuova build in latest
          echo "Aggiorno latest"
          rm -rf latest
          mkdir latest
          cp -r ../dist/* latest/

          # Configura Git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # Commit & push
          git add .
          git commit -m "Deploy new build: update latest and previous" || echo "⚠️ Nessuna modifica da commitare"
          git push origin gh-pages --force

          echo "Deploy completato con successo!"
