name: Build & Deploy Schema Editor

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout codice sorgente
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installa dipendenze
      - name: Install dependencies
        run: npm ci

      # Build progetto (ferma il job se fallisce)
      - name: Build project
        run: npm run build

      # Set version based on tag, PR or latest
      - name: Set version based on event type
        env:
          UNTRUSTED_GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            PACKAGE_VERSION="${{ github.ref_name }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PACKAGE_VERSION="PR-${UNTRUSTED_GITHUB_HEAD_REF}"
          else
            PACKAGE_VERSION="latest"
          fi
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"
          
      # Deploy latest & previous su gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ env.PACKAGE_VERSION }}
