name: Deploy Schema Editor

# Triggera il deploy su push al branch main
on:
  push:
    branches:
      - build-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installa le dipendenze
      - name: Install dependencies
        run: npm ci

      # Build del progetto
      - name: Build
        run: npm run build

      # Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
